library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(shinycssloaders)
library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(shinyWidgets)
library(DT)
library(shinydashboardPlus)

# location = na.omit(read.csv("./../../data/Ames_loc.csv"))
# df = read.csv('./../../data/cleaned_housing.csv')
# housing = merge(df, location, by="PID")
df_predictions = read.csv("./home_flipping.csv")
undervalued25 = read.csv('./undervalued_homes.csv')
df_coefs = read_csv('./final_predictions.csv')
df_feats = read.csv('./final_features.csv')

