# library(sf)
# library(tigris)
library(mapview)
library(leaflet)
library(shinycssloaders)
library(dplyr)
library(tidyverse)
library(tidyr)
# library(lubridate)
library(shinyWidgets)
library(DT)
library(htmltools)
library(glue)

df_predictions = read_csv("./home_flipping.csv")
undervalued25 = read_csv('./undervalued_homes.csv')
df_coefs = read_csv('./final_predictions.csv')
df_feats = read_csv('./final_features.csv')
df_places = read_csv('./Ames_places.csv')
