# AirBNB RProject

library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(shinycssloaders)
library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(shinyWidgets)
library(DT)
# remotes::install_github("deepanshu88/summaryBox")
library(summaryBox)
library(shinythemes)

location = na.omit(read.csv("./../../data/Ames_loc.csv"))
df = read.csv('./../../data/cleaned_housing.csv')
housing = merge(df, location, by="PID")
df_predictions = read.csv("./home_flipping.csv")
undervalued25 = read.csv('./undervalued25.csv')
